### ISSUE TITLE
maximum recursion depth exceeded while processing keras.applications.resnet50

### ISSUE THREAD

**Issue by isaacgerg** [brianlow/keras_diagram#6]
Used keras-diagram 1.0.5 pulled from pip.

Loaded resnet50 model from keras. Then, used keras_diagram.ascii(model) results in maximum recursion depth exceeded.

**Comment by isaacgerg** [comment]
Any progress on this?

**Comment by kunc** [comment]
I have the same problem (also with resnet50) - I have wanted to write the model summary to string without the need to redirect the stdout (viz http://stackoverflow.com/questions/41665799/keras-model-summary-object-to-string). Would be possible to modify the code into an iterative version so this doesn't happen?

Btw, I have tried setting `sys.setrecursionlimit(10000)` but that resulted only in another exception:
`  File "C:\Anaconda3\lib\site-packages\keras_diagram\diagram.py", line 56, in canvas
    c = child.canvas()
  File "C:\Anaconda3\lib\site-packages\keras_diagram\diagram.py", line 61, in canvas
    a = Arrows(canvas.width())
  File "C:\Anaconda3\lib\site-packages\keras_diagram\diagram.py", line 135, in __init__
    self.line1 = create_string_buffer(' ' * width)
  File "C:\Anaconda3\lib\ctypes\__init__.py", line 63, in create_string_buffer
    raise TypeError(init)
TypeError:                                                                                         
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000002559EA8C9B0>>
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 582, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'`
